### ISSUE TITLE
Does not connect: Invalid header length

### ISSUE THREAD

**Issue by AdvancedStyle** [zcoinofficial/electrum-xzc#31]
Electrum will not connect to any servers and is showing the below errors repeatedly in terminal.

```
E/i | electrum_xzc.interface.[electrumx.zcoin.io:50002] | Exception in wrapper_func: InvalidHeader('Invalid header length: 180',)
Traceback (most recent call last):
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/util.py", line 902, in wrapper
    return await func(*args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 331, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 355, in run
    await self.open_session(ssl_context)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 464, in open_session
    await group.spawn(self.monitor_connection)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/verifier.py", line 63, in _start_tasks
    await group.spawn(self.main)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/verifier.py", line 72, in main
    await self._request_proofs()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/verifier.py", line 87, in _request_proofs
    header = self.blockchain.read_header(tx_height)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 194, in func_wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 487, in read_header
    return deserialize_header(h, height)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 62, in deserialize_header
    raise InvalidHeader('Invalid header length: {}'.format(len(s)))
electrum_xzc.blockchain.InvalidHeader: Invalid header length: 180
E/i | electrum_xzc.interface.[electrumx01.zcoin.io:50002] | Exception in wrapper_func: AssertionError()
Traceback (most recent call last):
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/util.py", line 902, in wrapper
    return await func(*args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 331, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 355, in run
    await self.open_session(ssl_context)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 464, in open_session
    await group.spawn(self.monitor_connection)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 501, in run_fetch_blocks
    await self._process_header_at_tip()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 513, in _process_header_at_tip
    _, height = await self.step(height, header)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 571, in step
    return await self._resolve_potential_chain_fork_given_forkpoint(good, bad, bad_header)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 621, in _resolve_potential_chain_fork_given_forkpoint
    b = forkfun(bad_header)  # type: Blockchain
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 270, in fork
    self.save_header(header)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 194, in func_wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 459, in save_header
    assert self.size() == header.get('block_height') - self.forkpoint
AssertionError
E/i | electrum_xzc.interface.[electrumx.zcoin.io:50002] | Exception in wrapper_func: InvalidHeader('Invalid header length: 180',)
Traceback (most recent call last):
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/util.py", line 902, in wrapper
    return await func(*args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 331, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 355, in run
    await self.open_session(ssl_context)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/interface.py", line 464, in open_session
    await group.spawn(self.monitor_connection)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/verifier.py", line 63, in _start_tasks
    await group.spawn(self.main)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/verifier.py", line 72, in main
    await self._request_proofs()
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/verifier.py", line 87, in _request_proofs
    header = self.blockchain.read_header(tx_height)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 194, in func_wrapper
    return func(self, *args, **kwargs)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 487, in read_header
    return deserialize_header(h, height)
  File "/tmp/.mount_electr1q1AiA/usr/lib/python3.6/site-packages/electrum_xzc/blockchain.py", line 62, in deserialize_header
    raise InvalidHeader('Invalid header length: {}'.format(len(s)))
electrum_xzc.blockchain.InvalidHeader: Invalid header length: 180

```

**Comment by a-bezrukov** [comment]
Chances are you are using an outdated version of Electrum-XZC. Please use the latest Electrum-XZC version, namely 3.3.8.

**Comment by AdvancedStyle** [comment]
I'm using electrum_xzc-3.3.8-x86_64.AppImage

**Comment by a-bezrukov** [comment]
Please cleanup your "forks" dir, like this: `rm -rf ~/.electrum-xzc/forks/*` . Please back up your wallet secret before cleaning the forks.

**Comment by AdvancedStyle** [comment]
I deleted "forks" dir, but it didn't help.

Then i deleted everything in ~/.electrum-xzc/  (except not wallets), and now it's working.
